SELECT licensenumber,
       licensetype,
       licenseissuedate,
       licenseexpirationdate,
       licensestatus,
       contactname,
       companyname,
       licenselink,
       permitnumber,
       permittype,
       permitdescription,
       permittypeofwork,
       permitcreateddate,
       permitissuedate,
       permitstatus,
       permitcompleteddate,
       inspectiontype,
       inspectionscheduledstartdate,
       inspectioncompleteddate,
       inspectionoutcome,
       inspectorname,
       address,
       inspectionprocessid,
       vioswhileopen,
       soleproprietor,
       'ECLIPSE' systemofrecord
FROM ecl_tl_permits_fpp_insp1
UNION
SELECT licensenumber,
       licensetype,
       licenseissuedate,
       licenseexpirationdate,
       licensestatus,
       contactname,
       companyname,
       posselink licenselink,
       permitnumber,
       permittype,
       permittypedesc permitdescription,
       permitworktype permittypeofwork,
       permitprocesseddate permitcreateddate,
       permitissuancedate permitissuedate,
       permitstatus,
       permitfinaleddate permitcompleteddate,
       inspectiondescription inspectiontype,
       inspectionscheduled inspectionscheduledstartdate,
       inspectioncompleted inspectioncompleteddate,
       inspectionstatus inspectionoutcome,
       inspectorname,
       address,
       apinspkey inspectionprocessid,
       vioswhileopen,
       soleproprietor,
       'HANSEN' systemofrecord
FROM contlic_permits_fpp_insp