SELECT tl.LICENSENUMBER ,
  tl.LICENSETYPE ,
  tl.CONTACTNAME LICENSECONTACTNAME,
  tl.COMPANYNAME LICENSECOMPANYNAME,
  tl.ISSUEDATE LicenseIssueDate,
  tl.EXPIRATIONDATE LicenseExpirationDate,
  tl.LICENSESTATUS ,
 -- 'https://eclipseprod.phila.gov/phillylmsprod/int/lms/Default.aspx#presentationId=2855291&objectHandle='||tl.objectid AS POSSELink,
  c.casenumber,
  c.listedas,
  c.casegroup,
  c.caseaddeddate,
  c.caseresolutioncode,
  c.caseresolutiondate,
  c.contractorprimary,
  c.contractorcapacity,
  c.contractorname,
  c.contactprimary,
  c.contactcapacity,
  c.contactname,
  c.contactorganization,
  c.address
FROM TRADE_LICENSES_ALL_MVW tl,
  TL_CASES_MVW c
WHERE tl.LICENSENUMBER = c.LICENSENUM (+)