SELECT DISTINCT     "PERMITNUMBER",
    "PERMITISSUANCEDATE",
    "INSPECTIONCOMPLETED",
    "INSPECTIONSTATUS",
    "INSPECTIONTYPE",
    "INSPECTIONDESCRIPTION",
    "INSPECTORNAME",
    "ADDRESS"
FROM
  (WITH temp AS
  (SELECT COUNT(*) OVER ()                        AS "ROWCOUNT",
    "PERMITNUMBER",
    "PERMITISSUANCEDATE",
    "INSPECTIONCOMPLETED",
    "INSPECTIONSTATUS",
    "INSPECTIONTYPE",
    "INSPECTIONDESCRIPTION",
    "INSPECTORNAME",
    "ADDRESS"
    from
  (SELECT DISTINCT 
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITNUMBER"                        AS "PERMITNUMBER",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITISSUANCEDATE"                  AS "PERMITISSUANCEDATE",
    CAST("GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTIONCOMPLETED" AS DATE)   AS "INSPECTIONCOMPLETED",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTIONSTATUS"                    AS "INSPECTIONSTATUS",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTIONTYPE"                      AS "INSPECTIONTYPE",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTIONDESCRIPTION"               AS "INSPECTIONDESCRIPTION",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTORNAME"                       AS "INSPECTORNAME",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."ADDRESS"                             AS "ADDRESS"
  FROM "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"
  WHERE "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."APINSPKEY" IS NOT NULL
  [[AND {{LICENSENUMBER}}]]
  [[AND {{LICENSEISSUEDATE}}]]
  [[AND {{LICENSESTATUS}}]]
  [[AND {{LICENSETYPE}}]]
  [[AND {{PERMITNUMBER}}]]
  [[AND {{PERMITISSUANCEDATE}}]]
  [[AND {{PERMITSTATUS}}]]
  [[AND {{PERMITTYPE}}]]
  [[AND {{PERMITWORKTYPE}}]]
  [[AND {{INSPECTIONCOMPLETED}}]]
  [[AND {{INSPECTIONSTATUS}}]]
  [[AND {{INSPECTIONTYPE}}]]
  ))
SELECT (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITNUMBER"
    ELSE NULL
  END) AS "PERMITNUMBER",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITISSUANCEDATE"
    ELSE NULL
  END) AS "PERMITISSUANCEDATE",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "INSPECTIONCOMPLETED"
    ELSE NULL
  END) AS "INSPECTIONCOMPLETED",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "INSPECTIONSTATUS"
    ELSE 'Sorry, this table can only report 2,000 or fewer results. Adjust the filters to reduce the number of results returned.'
  END) AS "INSPECTIONSTATUS",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "INSPECTIONTYPE"
    ELSE NULL
  END) AS "INSPECTIONTYPE",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "INSPECTIONDESCRIPTION"
    ELSE NULL
  END) AS "INSPECTIONDESCRIPTION",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "INSPECTORNAME"
    ELSE NULL
  END) AS "INSPECTORNAME",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "ADDRESS"
    ELSE NULL
  END) AS "ADDRESS"
FROM temp
  ) sub
 ORDER BY "PERMITISSUANCEDATE", "INSPECTIONCOMPLETED" ASC