SELECT DISTINCT "LICENSENUMBER",
    "PERMITNUMBER",
    "PERMITTYPE",
    "PERMITTYPEDESC",
    "PERMITWORKTYPE",
    "PERMITISSUANCEDATE",
    "PERMITSTATUS",
    "PERMITFINALEDDATE",
    "ADDRESS",
    "FAILEDINSPECTIONS",
    "PARTIALPASSEDINSPECTIONS"
FROM
  (WITH temp AS
  (SELECT COUNT(*) OVER () AS "ROWCOUNT",
    "LICENSENUMBER",
    "PERMITNUMBER",
    "PERMITTYPE",
    "PERMITTYPEDESC",
    "PERMITWORKTYPE",
    "PERMITISSUANCEDATE",
    "PERMITSTATUS",
    "PERMITFINALEDDATE",
    "ADDRESS",
    "FAILEDINSPECTIONS",
    "PARTIALPASSEDINSPECTIONS"
  FROM
    (SELECT "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSENUMBER"             AS "LICENSENUMBER",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITNUMBER"                    AS "PERMITNUMBER",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITTYPE"                      AS "PERMITTYPE",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITTYPEDESC"                  AS "PERMITTYPEDESC",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITWORKTYPE"                  AS "PERMITWORKTYPE",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITISSUANCEDATE"              AS "PERMITISSUANCEDATE",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITSTATUS"                    AS "PERMITSTATUS",
      CAST("GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITFINALEDDATE" AS DATE) AS "PERMITFINALEDDATE",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."ADDRESS"                         AS "ADDRESS",
      SUM(
      CASE
        WHEN "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTIONSTATUS" = 'Failed'
        THEN 1
        ELSE 0
      END) AS "FAILEDINSPECTIONS",
      SUM(
      CASE
        WHEN "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTIONSTATUS" = 'Partial Passed'
        THEN 1
        ELSE 0
      END) AS "PARTIALPASSEDINSPECTIONS"
    FROM "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"
      [[WHERE {{LICENSENUMBER}}]]
      [[AND {{LICENSEISSUEDATE}}]]
      [[AND {{LICENSESTATUS}}]]
      [[AND {{LICENSETYPE}}]]
      [[AND {{PERMITNUMBER}}]]
      [[AND {{PERMITISSUANCEDATE}}]]
      [[AND {{PERMITSTATUS}}]]
      [[AND {{PERMITTYPE}}]]
      [[AND {{PERMITWORKTYPE}}]]
      [[AND {{INSPECTIONCOMPLETED}}]]
      [[AND {{INSPECTIONSTATUS}}]]
      [[AND {{INSPECTIONTYPE}}]]
    GROUP BY "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSENUMBER",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITNUMBER",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITTYPE",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITTYPEDESC",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITWORKTYPE",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITISSUANCEDATE",
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITSTATUS",
      CAST("GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITFINALEDDATE" AS DATE),
      "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."ADDRESS"
    )
  )
SELECT (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "LICENSENUMBER"
    ELSE NULL
  END) AS "LICENSENUMBER",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITNUMBER"
    ELSE NULL
  END) AS "PERMITNUMBER",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITTYPE"
    ELSE 'Sorry, this table can only report 2,000 or fewer results. Adjust the filters to reduce the number of results returned.'
  END) AS "PERMITTYPE",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITTYPEDESC"
    ELSE NULL
  END) AS "PERMITTYPEDESC",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITWORKTYPE"
    ELSE NULL
  END) AS "PERMITWORKTYPE",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITISSUANCEDATE"
    ELSE NULL
  END) AS "PERMITISSUANCEDATE",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITSTATUS"
    ELSE NULL
  END) AS "PERMITSTATUS",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITFINALEDDATE"
    ELSE NULL
  END) AS "PERMITFINALEDDATE",
    (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "ADDRESS"
    ELSE NULL
  END) AS "ADDRESS",
      (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "FAILEDINSPECTIONS"
    ELSE NULL
  END) AS "FAILEDINSPECTIONS",
      (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PARTIALPASSEDINSPECTIONS"
    ELSE NULL
  END) AS "PARTIALPASSEDINSPECTIONS"
FROM temp
  ) sub
ORDER BY "LICENSENUMBER", "PERMITISSUANCEDATE" ASC