SELECT DISTINCT "LICENSENUMBER" AS "License Number",
    "LICENSETYPE",
    "LICENSESTATUS",
    "LICENSEISSUEDATE",
    "LICENSEEXPIRATIONDATE",
    "PERMITSISSUED",
    "FAILEDINSPECTIONS",
    "PARTIALPASSEDINSPECTIONS",
    "CONTACTNAME",
    "COMPANYNAME",
    "POSSELINK"
FROM
  (WITH temp AS
  (SELECT COUNT(*) OVER () AS "ROWCOUNT",
    "LICENSENUMBER",
    "LICENSETYPE",
    "LICENSESTATUS",
    "LICENSEISSUEDATE",
    "LICENSEEXPIRATIONDATE",
    "PERMITSISSUED",
    "FAILEDINSPECTIONS",
    "PARTIALPASSEDINSPECTIONS",
    "CONTACTNAME",
    "COMPANYNAME",
    "POSSELINK"
  FROM
    (SELECT "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSENUMBER"               AS "LICENSENUMBER",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSETYPE"                         AS "LICENSETYPE",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSESTATUS"                       AS "LICENSESTATUS",
    CAST("GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSEISSUEDATE" AS      DATE) AS "LICENSEISSUEDATE",
    CAST("GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSEEXPIRATIONDATE" AS DATE) AS "LICENSEEXPIRATIONDATE",
    COUNT(DISTINCT "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."PERMITNUMBER")        AS "PERMITSISSUED",
    SUM(
      CASE
        WHEN "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTIONSTATUS" = 'Failed'
        THEN 1
        ELSE 0
      END) AS "FAILEDINSPECTIONS",
      SUM(
      CASE
        WHEN "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."INSPECTIONSTATUS" = 'Partial Passed'
        THEN 1
        ELSE 0
      END) AS "PARTIALPASSEDINSPECTIONS",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."CONTACTNAME"                         AS "CONTACTNAME",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."COMPANYNAME"                         AS "COMPANYNAME",  
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."POSSELINK"                           AS "POSSELINK"
    FROM "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"
      [[WHERE {{LICENSENUMBER}}]]
      [[AND {{LICENSEISSUEDATE}}]]
      [[AND {{LICENSESTATUS}}]]
      [[AND {{LICENSETYPE}}]]
      [[AND {{PERMITNUMBER}}]]
      [[AND {{PERMITISSUANCEDATE}}]]
      [[AND {{PERMITSTATUS}}]]
      [[AND {{PERMITTYPE}}]]
      [[AND {{PERMITWORKTYPE}}]]
      [[AND {{INSPECTIONCOMPLETED}}]]
      [[AND {{INSPECTIONSTATUS}}]]
      [[AND {{INSPECTIONTYPE}}]]
    GROUP BY "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSENUMBER",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSETYPE",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSESTATUS",
    CAST("GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSEISSUEDATE" AS      DATE),
    CAST("GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."LICENSEEXPIRATIONDATE" AS DATE),
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."CONTACTNAME",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."COMPANYNAME",
    "GIS_LNI"."CONTLIC_PERMITS_FPP_INSP"."POSSELINK"
    )
  )
SELECT (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "LICENSENUMBER"
    ELSE NULL
  END) AS "LICENSENUMBER",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "LICENSETYPE"
    ELSE 'Sorry, this table can only report 2,000 or fewer results. Adjust the filters to reduce the number of results returned.'
  END) AS "LICENSETYPE",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "LICENSESTATUS"
    ELSE NULL
  END) AS "LICENSESTATUS",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "LICENSEISSUEDATE"
    ELSE NULL
  END) AS "LICENSEISSUEDATE",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "LICENSEEXPIRATIONDATE"
    ELSE NULL
  END) AS "LICENSEEXPIRATIONDATE",
    (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PERMITSISSUED"
    ELSE NULL
  END) AS "PERMITSISSUED",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "FAILEDINSPECTIONS"
    ELSE NULL
  END) AS "FAILEDINSPECTIONS",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "PARTIALPASSEDINSPECTIONS"
    ELSE NULL
  END) AS "PARTIALPASSEDINSPECTIONS",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "CONTACTNAME"
    ELSE NULL
  END) AS "CONTACTNAME",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "COMPANYNAME"
    ELSE NULL
  END) AS "COMPANYNAME",
  (
  CASE
    WHEN "ROWCOUNT" <= 2000
    THEN "POSSELINK"
    ELSE NULL
  END) AS "POSSELINK"
FROM temp
  ) sub
ORDER BY "FAILEDINSPECTIONS" DESC