SELECT addressobjectid,
       casenumber,
       casetype,
       caseresponsibility,
       casepriority,
       investigationprocessid,
       investigationtype,
       investigationcreated,
       investigationscheduled,
       investigationcompleted,
       investigationresult,
       investigationoutcome,
       investigationstatus,
       findings,
       staffassigned,
       opa_account_num,
       address,
       zip,
       censustract,
       council_district,
       li_district,
       systemofrecord,
       sdo_cs.transform (sdo_geometry (2001, 2272, sdo_point_type (geocode_x, geocode_y, NULL), NULL, NULL), 4326).sdo_point.
       x lon,
       sdo_cs.transform (sdo_geometry (2001, 2272, sdo_point_type (geocode_x, geocode_y, NULL), NULL, NULL), 4326).sdo_point.
       y lat
FROM mvw_case_inv_internal