SELECT sla.JOBID,
  sla.PROCESSID,
  sla.jobtype,
  sla.JOBCREATEDDATE,
  bds1.BUSINESSDAYSSINCE BDSinceJobCreated,
  sla.PROCESSDATECOMPLETED,
  (
  CASE
    WHEN sla.PROCESSDATECOMPLETED is not null
    THEN 1
    ELSE 0
  END ) ProcessCompleted,
  bds2.BUSINESSDAYSSINCE BDSinceProcessCompleted,
  bds2.BUSINESSDAYSSINCE - bds1.BUSINESSDAYSSINCE BDOpen,
  (
  CASE
    WHEN bds2.BUSINESSDAYSSINCE - bds1.BUSINESSDAYSSINCE <= 2
    THEN 1
    ELSE 0
  END ) WithinSLA
FROM SLA_TL sla,
  BUSINESS_DAYS_SINCE_2017 bds1,
  BUSINESS_DAYS_SINCE_2017 bds2
WHERE TO_DATE(TO_CHAR(sla.JOBCREATEDDATE, 'mm')
  || TO_CHAR(sla.JOBCREATEDDATE, 'dd')
  || TO_CHAR(sla.JOBCREATEDDATE, 'yyyy'), 'MMDDYYYY') = bds1.DATEOFYEAR (+)
AND TO_DATE(TO_CHAR(sla.PROCESSDATECOMPLETED, 'mm')
  || TO_CHAR(sla.PROCESSDATECOMPLETED, 'dd')
  || TO_CHAR(sla.PROCESSDATECOMPLETED, 'yyyy'), 'MMDDYYYY') = bds2.DATEOFYEAR (+)