SELECT oi.BUSINESSADDRESS,
oi.LICENSENUMBER,
oi.LICENSETYPE,
oi.JOBNUMBER,
oi.INSPECTIONON,
oi.INSPECTIONTYPE,
oi.INSPECTIONOBJECTID,
oi.INSPECTIONCREATEDDATE,
oi.SCHEDULEDINSPECTIONDATE,
bds2.BUSINESSDAYSSINCE - bds1.BUSINESSDAYSSINCE BusDaysOverdue,
(
CASE
  WHEN bds2.BUSINESSDAYSSINCE - bds1.BUSINESSDAYSSINCE <= 10
  THEN '0-10'
  WHEN bds2.BUSINESSDAYSSINCE - bds1.BUSINESSDAYSSINCE BETWEEN 11 AND 20
  THEN '11-20'
  WHEN bds2.BUSINESSDAYSSINCE - bds1.BUSINESSDAYSSINCE BETWEEN 21 AND 100
  THEN '21-100'
  ELSE 'More than 100'
END) BusDaysOverdueCategories,
oi.inspector,
oi.link
FROM overdue_inspections_bl oi,
  BUSINESS_DAYS_SINCE_2016 bds1,
  BUSINESS_DAYS_SINCE_2016 bds2
WHERE TO_DATE(TO_CHAR(oi.scheduledinspectiondate, 'mm')
  || TO_CHAR(oi.scheduledinspectiondate, 'dd')
  || TO_CHAR(oi.scheduledinspectiondate, 'yyyy'), 'MMDDYYYY') = bds1.DATEOFYEAR (+)
AND TO_DATE(TO_CHAR(SYSDATE, 'mm')
  || TO_CHAR(SYSDATE, 'dd')
  || TO_CHAR(SYSDATE, 'yyyy'), 'MMDDYYYY') = bds2.DATEOFYEAR (+)