SELECT "CASENUMBER","CASEADDEDDATE","CASERESOLUTIONCODE","CASERESOLUTIONDATE","CASEGROUP","LASTCOMPLETEDINSP","LASTCOMPLETEDINSPSTATUS","LASTCOMPLETEDINSPINSPECTOR","NEXTSCHEDULEDINSP","NEXTSCHEDULEDINSPINSPECTOR","OVERDUEINSPSCHEDULEDDATE","OVERDUEINSPINSPECTOR","ZIP","COUNCILDISTRICT","OPSDISTRICT","CENSUSTRACT"
    
FROM CASES

WHERE CASERESOLUTIONDATE IS NOT NULL
AND CASERESOLUTIONCODE IS NOT NULL
AND CASERESOLUTIONCODE != '(none)'