SELECT "CASENUMBER","CASEADDEDDATE","CASERESOLUTIONCODE","CASERESOLUTIONDATE","CASEGROUP","LASTCOMPLETEDINSP","LASTCOMPLETEDINSPSTATUS","LASTCOMPLETEDINSPINSPECTOR","NEXTSCHEDULEDINSP","NEXTSCHEDULEDINSPINSPECTOR","OVERDUEINSPSCHEDULEDDATE","OVERDUEINSPINSPECTOR","ZIP","COUNCILDISTRICT","OPSDISTRICT","CENSUSTRACT"
    
FROM CASES
    
WHERE CASERESOLUTIONDATE IS NULL OR CASERESOLUTIONCODE IS NULL OR CASERESOLUTIONCODE = '(none)'